repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        types: [python]
        exclude: ^alembic/versions/
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests, types-redis, types-PyYAML, types-python-jose, types-authlib]

  # Custom hook to prevent accidental commits/pushes to template repository
  - repo: local
    hooks:
      - id: prevent-template-push
        name: Prevent Template Repository Operations
        entry: python scripts/prevent_template_push.py
        language: system
        stages: [commit, push]
        description: "Prevents accidental commits and pushes to the template repository" 