repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]

  # Temporarily disabled due to Alembic migration file type issues
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       types: [python] 