repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        types: [python]

  - repo: local
    hooks:
      - id: mypy-app
        name: mypy (app)
        entry: python -m mypy app
        language: system
        pass_filenames: false

 