# Export all user schemas
# Export error schemas
from .errors import (
    AuthenticationErrorDetail,
    AuthorizationErrorDetail,
    ConflictErrorDetail,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    ErrorType,
    RateLimitErrorDetail,
    ResourceErrorDetail,
    ServerErrorDetail,
    ValidationErrorDetail,
)
from .user import (
    EmailVerificationRequest,
    EmailVerificationResponse,
    OAuthLogin,
    OAuthUserInfo,
    Token,
    TokenData,
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
)

__all__ = [
    "EmailVerificationRequest",
    "EmailVerificationResponse",
    "OAuthLogin",
    "OAuthUserInfo",
    "Token",
    "TokenData",
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    # Error schemas
    "AuthenticationErrorDetail",
    "AuthorizationErrorDetail",
    "ConflictErrorDetail",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "ErrorType",
    "RateLimitErrorDetail",
    "ResourceErrorDetail",
    "ServerErrorDetail",
    "ValidationErrorDetail",
]
