"""Add OAuth and email verification fields

Revision ID: 2b2d3cd4001a
Revises: baa1c45958ec
Create Date: 2025-07-19 13:14:40.754048

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2b2d3cd4001a"
down_revision = "baa1c45958ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("users", sa.Column("oauth_provider", sa.String(), nullable=True))
    op.add_column("users", sa.Column("oauth_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("oauth_email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("verification_token", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("verification_token_expires", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_token_expires")
    op.drop_column("users", "verification_token")
    op.drop_column("users", "oauth_email")
    op.drop_column("users", "oauth_id")
    op.drop_column("users", "oauth_provider")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
