"""add_password_reset_fields

Revision ID: add_password_reset_fields
Revises: 2b2d3cd4001a
Create Date: 2025-07-20 09:33:41.134617

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "add_password_reset_fields"
down_revision = "2b2d3cd4001a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_reset_token", sa.String(), nullable=True),
    )
    op.add_column(
        "users", sa.Column("password_reset_token_expires", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_token_expires")
    op.drop_column("users", "password_reset_token")
    # ### end Alembic commands ###
