"""Add is_superuser field to User model

Revision ID: baa1c45958ec
Revises: 157866a0839e
Create Date: 2025-07-19 10:54:19.230379

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "baa1c45958ec"
down_revision = "157866a0839e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
