"""Authentication-related CRUD operations."""

from .api_key import (
    count_all_api_keys,
    count_user_api_keys,
    create_api_key,
    deactivate_api_key,
    get_all_api_keys,
    get_api_key_by_hash,
    get_api_key_by_id,
    get_user_api_keys,
    rotate_api_key,
    verify_api_key_in_db,
)
from .refresh_token import (
    cleanup_expired_tokens,
    enforce_session_limit,
    get_refresh_token_by_hash,
    get_user_session_count,
    get_user_sessions,
    revoke_all_user_sessions,
    revoke_refresh_token,
    revoke_refresh_token_by_hash,
    verify_refresh_token_in_db,
)
from .user import (
    authenticate_user,
    cancel_account_deletion,
    cancel_user_deletion,
    confirm_account_deletion,
    confirm_user_deletion,
    count_deleted_users,
    count_users,
    create_oauth_user,
    create_user,
    get_deleted_users,
    get_user_by_deletion_token,
    get_user_by_email,
    get_user_by_id,
    get_user_by_id_any_status,
    get_user_by_oauth_id,
    get_user_by_password_reset_token,
    get_user_by_username,
    get_user_by_verification_token,
    get_users,
    get_users_for_deletion_reminder,
    get_users_for_permanent_deletion,
    permanently_delete_user,
    request_account_deletion,
    reset_user_password,
    restore_user,
    schedule_user_deletion,
    soft_delete_user,
    update_deletion_token,
    update_password_reset_token,
    update_user_password,
    update_verification_token,
    verify_user,
)

__all__ = [
    # User CRUD (actual function names)
    "create_user",
    "get_user_by_email",
    "get_user_by_username",
    "get_user_by_id",
    "authenticate_user",
    "get_user_by_oauth_id",
    "create_oauth_user",
    "verify_user",
    "update_verification_token",
    "get_user_by_verification_token",
    "update_password_reset_token",
    "get_user_by_password_reset_token",
    "reset_user_password",
    "update_user_password",
    "update_deletion_token",
    "get_user_by_deletion_token",
    "schedule_user_deletion",
    "confirm_user_deletion",
    "cancel_user_deletion",
    "get_users_for_deletion_reminder",
    "get_users_for_permanent_deletion",
    "count_users",
    "soft_delete_user",
    "restore_user",
    "permanently_delete_user",
    "cancel_account_deletion",
    "confirm_account_deletion",
    "request_account_deletion",
    "get_user_by_id_any_status",
    "get_deleted_users",
    "count_deleted_users",
    "get_users",

    # API Key CRUD (actual function names)
    "create_api_key",
    "get_api_key_by_hash",
    "verify_api_key_in_db",
    "get_user_api_keys",
    "count_user_api_keys",
    "get_api_key_by_id",
    "deactivate_api_key",
    "rotate_api_key",
    "get_all_api_keys",
    "count_all_api_keys",

    # Refresh Token CRUD (actual function names)
    "create_refresh_token",
    "cleanup_expired_tokens",
    "get_refresh_token_by_hash",
    "revoke_refresh_token",
    "revoke_refresh_token_by_hash",
    "get_user_sessions",
    "get_user_session_count",
    "revoke_all_user_sessions",
    "verify_refresh_token_in_db",
    "enforce_session_limit",
]
